use axum::{
    Router,
    extract::Path,
    http::StatusCode,
    response::IntoResponse,
    routing::get,
};

use crate::auth::HtmlTemplate;
use crate::state::AppState;
use crate::templates::{
    AstralPlanesTemplate, ChakricSystemsTemplate, DemiurgeMythTemplate, EmanationTheoriesTemplate,
    EsotericMythologiesCosmologiesTemplate, GnosticAeonsTemplate, GreekDeityTemplate,
    GreekPantheonTemplate, PlatonicWorldSoulTemplate, SephirothicHierarchiesTemplate,
    SophiaTraditionsTemplate, TreeOfLifeCosmologyTemplate,
};

#[derive(Clone, Copy)]
pub struct GreekDeity {
    pub slug: &'static str,
    pub name: &'static str,
    pub category: &'static str,
    pub title: &'static str,
    pub domains: &'static str,
    pub symbols: &'static [&'static str],
    pub lineage: &'static str,
    pub overview: &'static str,
    pub myths: &'static [&'static str],
    pub worship: &'static [&'static str],
    pub themes: &'static [&'static str],
    pub roman_counterpart: &'static str,
}

pub const GREEK_DEITIES: &[GreekDeity] = &[
    GreekDeity { slug: "chaos", name: "Chaos", category: "Primordial", title: "The first void", domains: "The yawning gap before ordered creation", symbols: &["Vast void", "Primordial mist", "Unbounded potential"], lineage: "Self-originating source of the first divine generation.", overview: "Chaos is the primordial gap from which the first principles of reality emerge. In Hesiodic tradition, Chaos precedes ordered cosmos and makes the existence of all later divine lineages possible.", myths: &["In Theogony, Chaos appears before Gaia, Tartarus, and Eros.", "Chaos gives rise to Erebus and Nyx, who in turn generate further cosmic powers.", "Philosophical interpreters later treat Chaos as indeterminacy before form."], worship: &["Not generally worshipped with a major civic cult.", "Referenced in cosmogonic hymns and theological speculation.", "Invoked in late esoteric cosmologies as primordial potential."], themes: &["Origin", "Potentiality", "From disorder to order"], roman_counterpart: "No direct equivalent" },
    GreekDeity { slug: "gaia", name: "Gaia", category: "Primordial", title: "Earth Mother", domains: "Earth, fertility, foundational life-force", symbols: &["Earth", "Mountain", "Fruitful soil"], lineage: "Emerges after Chaos; mother of Uranus, the Titans, and many other beings.", overview: "Gaia is the living Earth and foundational mother of the Greek divine family. She births major cosmic powers and initiates dynastic change when she aids Cronus against Uranus.", myths: &["Births Uranus and joins with him to produce the Titans.", "Gives Cronus the sickle used against Uranus.", "Later supports forces opposing Zeus in some traditions, including the Giants."], worship: &["Ancient earth cults and oracular associations.", "Offerings tied to fertility and agricultural life.", "Sometimes linked with chthonic rites and foundation myths."], themes: &["Motherhood", "Generative power", "Cosmic continuity"], roman_counterpart: "Terra" },
    GreekDeity { slug: "uranus", name: "Uranus", category: "Primordial", title: "Sky Father", domains: "Sky vault, cosmic covering", symbols: &["Starry heaven", "Vault of sky", "Celestial canopy"], lineage: "Child and consort of Gaia; father of Titans, Cyclopes, and Hundred-Handers.", overview: "Uranus personifies the enclosing sky and the first dynastic male ruler. His suppression of offspring triggers the first major cycle of overthrow in Greek myth.", myths: &["Imprisons children within Gaia, causing cosmic imbalance.", "Overthrown and castrated by Cronus.", "From his blood and severed generative force, new beings arise."], worship: &["Limited civic worship compared with Olympians.", "Present in cosmogonic recitations.", "Symbolic in philosophical cosmology."], themes: &["Patriarchal rule", "Suppression and rebellion", "Generational succession"], roman_counterpart: "Caelus" },
    GreekDeity { slug: "tartarus", name: "Tartarus", category: "Primordial", title: "The abyss", domains: "Deep cosmic pit, prison beneath Hades", symbols: &["Abyss", "Subterranean prison", "Depth"], lineage: "Primordial depth appearing near creation; in some sources paired with Gaia.", overview: "Tartarus is both a deity and a place, representing the deepest abyss of the cosmos. It becomes the prison of defeated Titans and other monstrous threats.", myths: &["Named among earliest cosmic realities in Theogony.", "Used by Zeus to confine Titans after Titanomachy.", "Associated with punishment myths of impious figures."], worship: &["Not a standard recipient of public cult.", "Appears in mystery and eschatological narratives.", "Used symbolically for deepest spiritual descent."], themes: &["Punishment", "Cosmic depth", "Containment of chaos"], roman_counterpart: "Tartarus (retained)" },
    GreekDeity { slug: "eros", name: "Eros", category: "Primordial", title: "Primal attraction", domains: "Desire, generation, binding force", symbols: &["Bow", "Flame of desire", "Winged youth"], lineage: "In early cosmogony, self-arising force; in later myth often child of Aphrodite and Ares.", overview: "In primordial theology, Eros is the force that drives union and generation. Later traditions recast him as the personal god of erotic desire and irresistible attraction.", myths: &["As primal Eros, enables creation through attraction.", "In later myth, pierces gods and mortals with desire.", "Central to the tale of Eros and Psyche in Roman-era literature."], worship: &["Honored with Aphrodite in love cult contexts.", "Invoked in marriage and fertility settings.", "Frequent in poetry and mystery symbolism."], themes: &["Attraction", "Creative impulse", "Love as cosmic force"], roman_counterpart: "Cupid/Amor" },
    GreekDeity { slug: "nyx", name: "Nyx", category: "Primordial", title: "Night", domains: "Night, mystery, veiling darkness", symbols: &["Night sky", "Veil", "Stars"], lineage: "Born from Chaos; mother of many abstract powers including Hypnos and Thanatos.", overview: "Nyx is the personification of night and one of the most ancient powers. Even Zeus is said to respect or fear offending her.", myths: &["Bears major personifications such as Sleep and Death.", "Shelters Hypnos when Zeus is angered.", "Linked with oracular night and liminal states."], worship: &["Limited direct cult; honored in poetic invocations.", "Associated with nocturnal rites.", "Central to mystical symbolism of hidden wisdom."], themes: &["Liminality", "Mystery", "Power of darkness"], roman_counterpart: "Nox" },
    GreekDeity { slug: "erebus", name: "Erebus", category: "Primordial", title: "Darkness", domains: "Shadowed darkness between worlds", symbols: &["Gloom", "Shadow", "Underworld dusk"], lineage: "Born from Chaos; consort of Nyx.", overview: "Erebus represents deep darkness, especially the murky regions associated with the underworld. With Nyx he sires day-related powers, expressing cyclical balance.", myths: &["Parents Aether and Hemera in Hesiodic genealogy.", "Marks shadowed passage to underworld zones.", "Functions as cosmic counterpart to luminous realms."], worship: &["Rarely worshipped independently.", "Appears in funerary and cosmological language.", "Interpreted allegorically by philosophers."], themes: &["Darkness and contrast", "Thresholds", "Cosmic duality"], roman_counterpart: "Erebus (retained)" },
    GreekDeity { slug: "cronus", name: "Cronus", category: "Titan", title: "Titan king", domains: "Sovereignty of the Titan age, cyclical succession", symbols: &["Sickle", "Harvest blade", "Devouring father"], lineage: "Youngest Titan child of Gaia and Uranus; consort of Rhea; father of major Olympians.", overview: "Cronus leads the rebellion against Uranus and rules the Titan era. Fearing overthrow, he swallows his children until Zeus survives and defeats him in the Titanomachy.", myths: &["Castrates Uranus with Gaia's plan.", "Swallows offspring to prevent prophecy fulfillment.", "Defeated by Zeus and imprisoned in Tartarus in common tradition."], worship: &["Celebrated in Kronia festival (especially Athens).", "Linked with memory of a Golden Age.", "Syncretized with Roman Saturn."], themes: &["Power cycles", "Fear of succession", "Golden Age nostalgia"], roman_counterpart: "Saturn" },
    GreekDeity { slug: "rhea", name: "Rhea", category: "Titan", title: "Mother of Olympians", domains: "Motherhood, dynastic protection", symbols: &["Lion-drawn chariot", "Drum", "Mountain mother"], lineage: "Titan daughter of Gaia and Uranus; sister-consort of Cronus; mother of Olympians.", overview: "Rhea preserves the Olympian line by saving infant Zeus from Cronus. She embodies maternal strategy and continuity between Titan and Olympian generations.", myths: &["Hides Zeus in Crete and gives Cronus a stone to swallow.", "Associated with Curetes and sacred infant-protection rites.", "Blends with great-mother cult motifs in later antiquity."], worship: &["Cult activity in Crete and mainland sanctuaries.", "Linked with mountain and mother-goddess rites.", "Sometimes merged with Cybele imagery."], themes: &["Protection", "Maternal intelligence", "Dynastic transition"], roman_counterpart: "Ops" },
    GreekDeity { slug: "oceanus", name: "Oceanus", category: "Titan", title: "World-encircling river", domains: "Cosmic waters, river around earth", symbols: &["River", "Horned river-god", "Flowing stream"], lineage: "Titan son of Gaia and Uranus; consort of Tethys.", overview: "Oceanus represents the great river imagined to encircle the inhabited world. He fathers many river gods and Oceanids, becoming a source of life and boundary symbolism.", myths: &["Sires major water nymph lineages with Tethys.", "Usually remains apart from direct Titanomachy conflict.", "Appears in cosmographic and poetic geography."], worship: &["Invoked in oaths and water rituals.", "Resonant in maritime imagination.", "Referenced in cosmological teaching traditions."], themes: &["Boundary", "Flow", "Source of waters"], roman_counterpart: "Oceanus (retained)" },
    GreekDeity { slug: "hyperion", name: "Hyperion", category: "Titan", title: "Titan of high light", domains: "Heavenly light and observation", symbols: &["Radiance", "High sun", "Celestial watch"], lineage: "Titan son of Gaia and Uranus; father of Helios, Selene, and Eos with Theia.", overview: "Hyperion is an early personification of elevated, watchful light. His children become the principal luminaries of day, moon, and dawn.", myths: &["Named among original Titans.", "Fathers key celestial deities.", "Later overshadowed by Apollo and Helios traditions."], worship: &["Limited independent cult evidence.", "Present in genealogical theology.", "Used in poetic language for sunlike brilliance."], themes: &["Light", "Cosmic order", "Observation"], roman_counterpart: "Hyperion (retained)" },
    GreekDeity { slug: "themis", name: "Themis", category: "Titan", title: "Divine law", domains: "Sacred order, justice, right custom", symbols: &["Scales", "Council", "Oracle"], lineage: "Titan daughter of Gaia and Uranus; associated with Zeus as advisor/consort in some traditions.", overview: "Themis personifies divine order beyond human legislation. She underpins lawful assembly, right ritual, and prophetic legitimacy.", myths: &["Attends Zeus as counselor of cosmic order.", "Mother of the Horae and, in some genealogies, the Moirai.", "Connected to Delphi's pre-Apollonian oracular strata."], worship: &["Honored in sanctuaries associated with justice and assembly.", "Invoked in civic oaths and legal rhetoric.", "Appears in philosophical discussions of natural law."], themes: &["Order", "Law", "Legitimacy"], roman_counterpart: "Iustitia/Themis analogues" },
    GreekDeity { slug: "mnemosyne", name: "Mnemosyne", category: "Titan", title: "Memory", domains: "Memory, poetic recall, sacred transmission", symbols: &["Tablet", "Recitation", "Muse lineage"], lineage: "Titan daughter of Gaia and Uranus; mother of the nine Muses by Zeus.", overview: "Mnemosyne personifies memory as the foundation of culture and ritual continuity. Through the Muses, she gives rise to inspired speech, song, history, and learned tradition.", myths: &["Unites with Zeus over nine nights to bear nine Muses.", "Represents reliable recollection in oral culture.", "Invoked by poets to access sacred narrative memory."], worship: &["Cultic and poetic invocation before performance.", "Important to rhapsodic and educational tradition.", "Linked with spring shrines tied to inspiration."], themes: &["Memory", "Inspiration", "Cultural continuity"], roman_counterpart: "Moneta-related resonance" },
    GreekDeity { slug: "zeus", name: "Zeus", category: "Olympian", title: "King of the gods", domains: "Sky, thunder, kingship, oath-keeping", symbols: &["Thunderbolt", "Eagle", "Oak"], lineage: "Son of Cronus and Rhea; sibling of Hera, Poseidon, Demeter, Hestia, and Hades.", overview: "Zeus overthrows Titan rule and establishes Olympian sovereignty. He governs cosmic and social order, though myths also portray his passions, politics, and limits before fate.", myths: &["Leads Olympians in Titanomachy victory.", "Defeats Typhon to stabilize divine rule.", "Intervenes repeatedly in heroic cycles such as Troy."], worship: &["Panhellenic cults at Olympia and Dodona.", "Epithets tie him to weather, hospitality, and justice.", "Sacrifices and oath rituals central in civic religion."], themes: &["Authority", "Order and turbulence", "Fate versus sovereignty"], roman_counterpart: "Jupiter" },
    GreekDeity { slug: "hera", name: "Hera", category: "Olympian", title: "Queen of heaven", domains: "Marriage, queenship, legitimate lineage", symbols: &["Peacock", "Diadem", "Cow"], lineage: "Daughter of Cronus and Rhea; sister and wife of Zeus.", overview: "Hera is sovereign protector of marriage and dynastic legitimacy. Myth often depicts her as politically astute, jealous, and relentless against rivals to her status.", myths: &["Opposes Zeus's lovers and their children, including Heracles.", "Plays decisive roles in Trojan cycle alignments.", "Honored as protectress of lawful unions."], worship: &["Major sanctuaries at Argos and Samos.", "Marriage rites and women's festivals dedicated to her.", "Invoked in civic identity and royal ideology."], themes: &["Marriage", "Status and rivalry", "Female sovereignty"], roman_counterpart: "Juno" },
    GreekDeity { slug: "poseidon", name: "Poseidon", category: "Olympian", title: "Lord of the sea", domains: "Sea, earthquakes, horses", symbols: &["Trident", "Horse", "Wave"], lineage: "Son of Cronus and Rhea; brother of Zeus and Hades.", overview: "Poseidon rules marine realms and seismic force. He is both benefactor of sailors and source of sudden devastation, embodying unstable power.", myths: &["Contests Athena for patronage of Athens.", "Persecutes Odysseus after blinding Polyphemus.", "Creates horses and springs in regional myths."], worship: &["Coastal cults, sailor offerings, and horse-linked rites.", "Important to colonists and maritime cities.", "Invoked in earthquake appeasement contexts."], themes: &["Volatility", "Territorial rivalry", "Power of nature"], roman_counterpart: "Neptune" },
    GreekDeity { slug: "demeter", name: "Demeter", category: "Olympian", title: "Grain mother", domains: "Agriculture, grain, seasonal fertility", symbols: &["Wheat", "Torch", "Sheaf"], lineage: "Daughter of Cronus and Rhea; mother of Persephone by Zeus.", overview: "Demeter sustains agriculture and the civilizing gift of grain. Her grief over Persephone's abduction structures the seasonal cycle and underlies major mystery traditions.", myths: &["Searches for Persephone, causing famine.", "Negotiates seasonal return from underworld.", "Central divine figure in Eleusinian Mysteries."], worship: &["Panhellenic worship tied to harvest cycles.", "Eleusis as major initiatory cult center.", "Women-led rites for fertility and community."], themes: &["Life-death-renewal", "Maternal devotion", "Agrarian order"], roman_counterpart: "Ceres" },
    GreekDeity { slug: "athena", name: "Athena", category: "Olympian", title: "Strategic wisdom", domains: "Wisdom, strategy, crafts, civic protection", symbols: &["Owl", "Olive tree", "Aegis"], lineage: "Daughter of Zeus, born from his head after Metis episode.", overview: "Athena unites intellect, disciplined warfare, and skilled craft. She is patron of cities, especially Athens, and model of strategic, measured power.", myths: &["Wins patronage of Athens with olive gift.", "Guides heroes such as Odysseus and Perseus.", "Arbitrates craft and justice-themed myths."], worship: &["Major cult on Athenian Acropolis.", "Panathenaia festival celebrates civic identity.", "Invoked by artisans, statesmen, and soldiers."], themes: &["Reasoned power", "Civic order", "Technique and intelligence"], roman_counterpart: "Minerva" },
    GreekDeity { slug: "apollo", name: "Apollo", category: "Olympian", title: "Archer and oracle", domains: "Light, music, healing, prophecy", symbols: &["Lyre", "Laurel", "Bow"], lineage: "Son of Zeus and Leto; twin brother of Artemis.", overview: "Apollo governs harmony and precision across prophecy, music, medicine, and plague. He is radiant yet severe, binding beauty with exacting law.", myths: &["Claims Delphi after slaying Python.", "Punishes hubris in tales like Marsyas and Niobe.", "Associated with healing through Asclepian lineages."], worship: &["Delphi and Delos as major sanctuaries.", "Pythian games and oracular consultation.", "Invoked by poets, healers, and colonists."], themes: &["Measure", "Purification", "Prophetic truth"], roman_counterpart: "Apollo (retained)" },
    GreekDeity { slug: "artemis", name: "Artemis", category: "Olympian", title: "Lady of the wild", domains: "Hunt, wilderness, maidenhood, childbirth protection", symbols: &["Bow", "Deer", "Moon"], lineage: "Daughter of Zeus and Leto; twin sister of Apollo.", overview: "Artemis is guardian of untamed nature and liminal life stages. She protects young beings yet can punish transgression with sudden severity.", myths: &["Demands sacrifice in Agamemnon-Iphigenia cycle.", "Transforms Actaeon after voyeuristic violation.", "Assists women in childbirth despite maiden identity."], worship: &["Major cults at Brauron and Ephesus.", "Rites of passage for girls and youth.", "Hunting and boundary-land offerings."], themes: &["Wild autonomy", "Protection and punishment", "Liminal transitions"], roman_counterpart: "Diana" },
    GreekDeity { slug: "ares", name: "Ares", category: "Olympian", title: "Fury of battle", domains: "Violent war, bloodlust, conflict", symbols: &["Spear", "Shield", "Vulture"], lineage: "Son of Zeus and Hera.", overview: "Ares personifies the chaotic and destructive side of warfare, distinct from Athena's strategic warcraft. Myths often depict him as formidable but impulsive.", myths: &["Wounded in Trojan war narratives.", "Engages in affair with Aphrodite.", "Faces legal trial on the Areopagus in one tradition."], worship: &["Less universally beloved than other Olympians.", "Regional military cults in Sparta and Thrace-linked areas.", "Invoked for battlefield ferocity."], themes: &["Violence", "Impetuosity", "War's destructive face"], roman_counterpart: "Mars" },
    GreekDeity { slug: "aphrodite", name: "Aphrodite", category: "Olympian", title: "Lady of desire", domains: "Love, beauty, erotic force", symbols: &["Dove", "Rose", "Sea-shell"], lineage: "In one tradition born from sea-foam after Uranus episode; in another daughter of Zeus and Dione.", overview: "Aphrodite governs attraction that unites, destabilizes, and transforms gods and mortals alike. Her power reaches politics, lineage, and heroic destiny.", myths: &["Catalyzes Trojan War through judgment of Paris.", "Loves Adonis and laments his death.", "Married to Hephaestus while linked with Ares."], worship: &["Cult centers at Cyprus, Cythera, and Corinth.", "Rites range from civic marriage to sensual celebration.", "Invoked for fertility and social bonds."], themes: &["Attraction", "Beauty and danger", "Creative desire"], roman_counterpart: "Venus" },
    GreekDeity { slug: "hephaestus", name: "Hephaestus", category: "Olympian", title: "Divine smith", domains: "Fire, metallurgy, craftsmanship", symbols: &["Anvil", "Hammer", "Forge"], lineage: "Usually son of Hera alone or of Hera and Zeus.", overview: "Hephaestus is master artisan of Olympus, crafting divine weapons, automata, and regalia. Though physically marked in myth, he embodies technical genius and patient workmanship.", myths: &["Forges thunderbolts and heroic arms.", "Creates trap exposing Aphrodite and Ares.", "Returns to Olympus after estrangements in family myths."], worship: &["Strong artisan and smith devotion.", "Hephaistia festivals, especially in Athens/Lemnos.", "Linked with volcanic and industrial fire."], themes: &["Skill", "Resilience", "Creative technology"], roman_counterpart: "Vulcan" },
    GreekDeity { slug: "hermes", name: "Hermes", category: "Olympian", title: "Messenger and guide", domains: "Communication, trade, travel, trickery, psychopomp", symbols: &["Caduceus", "Winged sandals", "Traveler's cap"], lineage: "Son of Zeus and Maia.", overview: "Hermes moves between worlds as messenger, negotiator, and escort of souls. He governs exchange systems—linguistic, economic, and spiritual.", myths: &["As infant, steals Apollo's cattle and invents the lyre.", "Guides souls to underworld as psychopomp.", "Assists heroes through clever mediation."], worship: &["Herm pillars at roads, homes, and marketplaces.", "Invoked by merchants, athletes, and travelers.", "Honored in boundary and transition rituals."], themes: &["Mobility", "Cunning intelligence", "Mediation"], roman_counterpart: "Mercury" },
    GreekDeity { slug: "dionysus", name: "Dionysus", category: "Olympian", title: "God of ecstasy", domains: "Wine, ecstasy, theater, altered consciousness", symbols: &["Vine", "Thyrsus", "Leopard"], lineage: "Son of Zeus and Semele; in myth undergoes unusual birth and wandering initiation.", overview: "Dionysus dissolves rigid social boundaries through intoxication, ritual frenzy, and dramatic revelation. He is both liberating and terrifying when denied proper recognition.", myths: &["Rescues Semele and affirms divine maternity.", "Punishes Pentheus in Bacchae cycle.", "Spreads ecstatic cult across Greek world."], worship: &["Dionysia festivals central to theater culture.", "Maenadic and mystery-inflected rites.", "Linked with wine production and communal catharsis."], themes: &["Ecstasy", "Boundary dissolution", "Divine madness and renewal"], roman_counterpart: "Bacchus/Liber" },
    GreekDeity { slug: "hestia", name: "Hestia", category: "Olympian", title: "Sacred hearth", domains: "Hearth fire, domestic and civic continuity", symbols: &["Hearth", "Flame", "Home altar"], lineage: "Eldest child of Cronus and Rhea in many traditions.", overview: "Hestia embodies the steady center of household and polis. Unlike dramatic Olympian narratives, her power is quiet permanence and ritual cohesion.", myths: &["Maintains perpetual sacred flame.", "Receives first and last share in sacrificial offerings.", "Sometimes yields Olympian seat to Dionysus in later lists."], worship: &["Universal hearth offerings in homes and cities.", "Core role in civic prytaneion fires.", "Invoked in rites opening and closing sacrifices."], themes: &["Stability", "Domestic sanctity", "Civic continuity"], roman_counterpart: "Vesta" },
    GreekDeity { slug: "nymphs", name: "Nymphs", category: "Minor Deities", title: "Spirits of place", domains: "Rivers, trees, springs, mountains, groves", symbols: &["Spring water", "Tree", "Meadow"], lineage: "Numerous local lineages tied to natural features and river-god families.", overview: "Nymphs are localized divine presences animating landscapes. They mediate fertility, inspiration, and danger in intimate contact with human communities.", myths: &["Appear as companions of Artemis, Pan, and Dionysus.", "Naiads, Dryads, and Oreads anchor specific ecologies.", "Can bless, seduce, or punish disrespectful humans."], worship: &["Shrines at springs, caves, and groves.", "Offerings of milk, honey, and small votives.", "Embedded in pastoral and healing cult practice."], themes: &["Sacred landscape", "Locality", "Nature's personhood"], roman_counterpart: "Nymphae" },
    GreekDeity { slug: "pan", name: "Pan", category: "Minor Deities", title: "Goat-footed wild god", domains: "Pastoral wilds, herds, rustic music, panic", symbols: &["Syrinx pipes", "Goat", "Mountain"], lineage: "Usually son of Hermes with varying maternal traditions.", overview: "Pan rules liminal wilderness and shepherd life, inspiring both delight and sudden terror. His raw presence represents untamed vitality outside city order.", myths: &["Invents panpipes after Syrinx myth.", "Associated with sudden fear (panic) in battle and wilderness.", "Joins Dionysian retinues and Arcadian cult narratives."], worship: &["Strong cult in Arcadia and rustic sanctuaries.", "Offerings from shepherd communities.", "Invoked for fertility of flocks and fields."], themes: &["Wildness", "Erotic pursuit", "Ecstatic rusticity"], roman_counterpart: "Faunus/Pan" },
    GreekDeity { slug: "helios", name: "Helios", category: "Minor Deities", title: "Solar charioteer", domains: "Sun's daily course, all-seeing witness", symbols: &["Sun chariot", "Radiant crown", "Horses"], lineage: "Titan son of Hyperion and Theia; sibling of Selene and Eos.", overview: "Helios personifies the visible sun traversing heaven each day. As all-seeing witness, he appears in oath and justice contexts before Apollo absorbs many solar roles.", myths: &["Drives sun chariot across sky.", "Father of Phaethon, whose failed drive scorches earth.", "Reports Persephone's abduction to Demeter."], worship: &["Cult strong at Rhodes and related island traditions.", "Solar invocations in oath and healing contexts.", "Linked to monumental sun iconography."], themes: &["Visibility", "Witness", "Cosmic rhythm"], roman_counterpart: "Sol" },
    GreekDeity { slug: "selene", name: "Selene", category: "Minor Deities", title: "Moon goddess", domains: "Moon, night light, cyclical time", symbols: &["Crescent moon", "Silver chariot", "Night glow"], lineage: "Titan daughter of Hyperion and Theia.", overview: "Selene is the personified moon, marking cyclical time, romance, and nocturnal beauty. She bridges cosmic regularity and intimate mythic longing.", myths: &["Loves Endymion and beholds him in eternal sleep.", "Traverses sky by moon-chariot.", "Interacts with lunar cult cycles and calendrical rites."], worship: &["Invoked in lunar observances and magic traditions.", "Connected with women's cycles and timing rituals.", "Blended with Artemis and Hecate in later triads."], themes: &["Cycles", "Nocturnal illumination", "Longing"], roman_counterpart: "Luna" },
    GreekDeity { slug: "nike", name: "Nike", category: "Personification", title: "Victory", domains: "Victory in battle, games, and civic achievement", symbols: &["Wings", "Wreath", "Palm branch"], lineage: "Daughter of Pallas and Styx; ally of Zeus.", overview: "Nike is the swift embodiment of victory granted by divine favor and disciplined excellence. She appears with Zeus and Athena in triumphal iconography.", myths: &["Supports Zeus during Titanomachy through Styx lineage loyalty.", "Frequently accompanies Athena as victorious aspect.", "Embodies moment of decisive success."], worship: &["Statues and dedications in victory monuments.", "Athena Nike cult on Athenian Acropolis.", "Invoked by athletes and generals."], themes: &["Triumph", "Merit and favor", "Public glory"], roman_counterpart: "Victoria" },
    GreekDeity { slug: "nemesis", name: "Nemesis", category: "Personification", title: "Retributive balance", domains: "Retribution, proportion, correction of hubris", symbols: &["Scales", "Bridle", "Whip"], lineage: "Genealogies vary; often linked to Night or Oceanid lines.", overview: "Nemesis restores balance when arrogance or excess violates rightful measure. She ensures that prosperity and pride remain bounded by moral order.", myths: &["Pursues those guilty of hubris.", "Associated in some traditions with Helen's birth narrative.", "Functions as cosmic counterforce to unchecked fortune."], worship: &["Cult center at Rhamnous in Attica.", "Invoked in legal and moral discourse.", "Appears in civic reflection on justice."], themes: &["Measure", "Retribution", "Moral equilibrium"], roman_counterpart: "Invidia/Nemesis" },
    GreekDeity { slug: "iris", name: "Iris", category: "Personification", title: "Rainbow messenger", domains: "Rainbow, divine communication", symbols: &["Rainbow", "Herald staff", "Winged motion"], lineage: "Daughter of Thaumas and Electra.", overview: "Iris carries messages across sky and sea, especially for Hera. She embodies graceful transit between divine and mortal spheres.", myths: &["Acts as Hera's swift envoy.", "Bridges Olympus and battlefield in epic narratives.", "Associated with rainbow as visible sign of passage."], worship: &["Less formal cult than Olympian messengers.", "Present in poetic and ritual invocations.", "Iconographically linked with heraldic service."], themes: &["Communication", "Mediation", "Celestial bridge"], roman_counterpart: "Iris (retained)" },
    GreekDeity { slug: "hecate", name: "Hecate", category: "Personification/Chthonic", title: "Mistress of crossroads", domains: "Magic, liminal thresholds, night, spirits", symbols: &["Torches", "Crossroads", "Keys"], lineage: "Titan lineage through Perses and Asteria in Hesiod.", overview: "Hecate governs liminal spaces where choices, spirits, and unseen forces converge. She is honored in domestic protection, magic, and underworld-adjacent rites.", myths: &["Aids Demeter in search for Persephone.", "Associated with night processions and ghostly retinues.", "Develops triple-form iconography in later periods."], worship: &["Household and crossroads offerings (deipnon).", "Invoked in magical papyri and protective rites.", "Important in later mystery and witchcraft traditions."], themes: &["Liminality", "Protection", "Occult knowledge"], roman_counterpart: "Trivia" },
    GreekDeity { slug: "muses", name: "The Muses", category: "Minor Deities", title: "Inspirers of arts and sciences", domains: "Poetry, music, history, dance, sacred knowledge", symbols: &["Lyre", "Scroll", "Chorus"], lineage: "Nine daughters of Zeus and Mnemosyne.", overview: "The Muses transmit inspired speech and disciplined artistry. They anchor memory, education, and cultural continuity in Greek thought.", myths: &["Born after nine nights of Zeus and Mnemosyne.", "Preside over poetic contests and sacred song.", "Engage in myths of rivalry and artistic punishment."], worship: &["Helicon and Pieria as prominent cult landscapes.", "Invoked at the start of epic and lyric works.", "Linked to philosophical and scholarly communities."], themes: &["Inspiration", "Learning", "Art as sacred vocation"], roman_counterpart: "Musae" },
    GreekDeity { slug: "hades", name: "Hades", category: "Chthonic", title: "Lord of the dead", domains: "Underworld rule, wealth beneath earth", symbols: &["Bident", "Helm of invisibility", "Cypress"], lineage: "Son of Cronus and Rhea; brother of Zeus and Poseidon.", overview: "Hades governs the underworld as stern but lawful sovereign rather than embodiment of evil. His realm structures afterlife order and chthonic justice.", myths: &["Abducts Persephone, creating seasonal myth cycle.", "Rules shades and judges with underworld officials.", "Possesses wealth symbolism through subterranean resources."], worship: &["Names and rites often euphemistic due reverence/fear.", "Chthonic sacrifices performed differently from Olympian ones.", "Invoked in funerary and oath contexts."], themes: &["Mortality", "Sovereignty below", "Fear and respect"], roman_counterpart: "Pluto/Dis" },
    GreekDeity { slug: "persephone", name: "Persephone", category: "Chthonic", title: "Queen below and maiden above", domains: "Underworld queenship, seasonal return", symbols: &["Pomegranate", "Torch", "Spring flower"], lineage: "Daughter of Demeter and Zeus; wife of Hades.", overview: "Persephone bridges life and death as both spring maiden and underworld queen. Her cyclical movement explains seasonal renewal and underpins mystery initiation.", myths: &["Abducted by Hades with Zeus's consent in core myth.", "Eats pomegranate seeds binding part-year return below.", "Central figure in Eleusinian initiatory theology."], worship: &["Major role in Eleusinian Mysteries.", "Invoked in fertility and afterlife rites.", "Cult language emphasizes dual identity."], themes: &["Cycle", "Transformation", "Threshold between worlds"], roman_counterpart: "Proserpina" },
    GreekDeity { slug: "thanatos", name: "Thanatos", category: "Chthonic", title: "Peaceful death", domains: "Personification of death", symbols: &["Inverted torch", "Wings", "Funerary garland"], lineage: "Son of Nyx; twin brother of Hypnos.", overview: "Thanatos personifies death's inevitable closure, often contrasted with violent death spirits. He appears as a necessary cosmic function, not moral evil.", myths: &["Outwitted by Sisyphus, briefly interrupting mortal death.", "Opposed by Heracles in rescuing Alcestis.", "Paired with Hypnos in art and poetry."], worship: &["No broad civic cult; present in funerary iconography.", "Invoked in tragic and philosophical literature.", "Symbolic in meditations on mortality."], themes: &["Inevitability", "Boundary of life", "Cosmic necessity"], roman_counterpart: "Mors" },
    GreekDeity { slug: "hypnos", name: "Hypnos", category: "Chthonic", title: "Sleep", domains: "Sleep, dreams, restorative unconsciousness", symbols: &["Poppy", "Winged youth", "Night cave"], lineage: "Son of Nyx; twin brother of Thanatos.", overview: "Hypnos embodies sleep as a liminal state between waking life and deathlike stillness. He is gentle yet potent, able to overpower gods when needed.", myths: &["Lulls Zeus at Hera's request.", "Dwells in a dim cave near dream rivers in poetic accounts.", "Associated with Oneiroi, the dream spirits."], worship: &["Limited independent public cult.", "Important in healing/incubation sanctuaries through dream practice.", "Frequent in literary invocations of rest."], themes: &["Rest", "Dream gateway", "Liminal consciousness"], roman_counterpart: "Somnus" },
    GreekDeity { slug: "clotho", name: "Clotho", category: "Chthonic", title: "Spinner of life thread", domains: "Destiny's beginning", symbols: &["Spindle", "Thread", "Loom"], lineage: "One of the three Moirai (Fates); genealogies vary.", overview: "Clotho initiates mortal life by spinning each person's thread. She represents beginnings granted within an ordered destiny framework.", myths: &["Works with Lachesis and Atropos in allotting fate.", "Appears in myths emphasizing inescapable destiny.", "Occasionally depicted among birth-related divine attendants."], worship: &["Venerated with the Moirai in civic and household rites.", "Invoked during transitions and birth concerns.", "Present in funerary and moral literature."], themes: &["Beginning", "Predestination", "Cosmic order"], roman_counterpart: "Nona (partial)" },
    GreekDeity { slug: "lachesis", name: "Lachesis", category: "Chthonic", title: "Allotter of measure", domains: "Measured span of life", symbols: &["Measuring rod", "Scroll of lots", "Thread length"], lineage: "One of the three Moirai (Fates).", overview: "Lachesis assigns the proportion and course of each life thread. She reflects the idea that destiny has structure, sequence, and allotted scope.", myths: &["Distributes lots in eschatological philosophical myths.", "Works between Clotho's spinning and Atropos's cutting.", "Embodies measured inevitability."], worship: &["Shared Moirai cult observances.", "Referenced in moral-philosophical reflections on fate.", "Invoked in rites seeking favorable allotment."], themes: &["Measure", "Allocation", "Life-course"], roman_counterpart: "Decima (partial)" },
    GreekDeity { slug: "atropos", name: "Atropos", category: "Chthonic", title: "The unturning one", domains: "Finality of death and destiny", symbols: &["Shears", "Cut thread", "Final decree"], lineage: "One of the three Moirai (Fates).", overview: "Atropos ends each life by cutting its thread, representing irreversible closure. Her name conveys fate's unbending endpoint.", myths: &["Completes the work of the Fates with decisive cut.", "Appears in depictions of unavoidable death.", "Associated with stern necessity in tragedy."], worship: &["Honored with Moirai in fate-oriented offerings.", "Remembered in funeral symbolism.", "Invoked in reflections on mortality and acceptance."], themes: &["Finality", "Necessity", "Irreversibility"], roman_counterpart: "Morta" },
];

pub fn routes() -> Router<AppState> {
    Router::new()
        .route("/", get(hub))
        .route("/gnostic-aeons", get(gnostic_aeons))
        .route("/demiurge-myth", get(demiurge_myth))
        .route("/sophia-traditions", get(sophia_traditions))
        .route("/tree-of-life-cosmology", get(tree_of_life_cosmology))
        .route("/emanation-theories", get(emanation_theories))
        .route("/platonic-world-soul", get(platonic_world_soul))
        .route("/astral-planes", get(astral_planes))
        .route("/chakric-systems", get(chakric_systems))
        .route("/sephirothic-hierarchies", get(sephirothic_hierarchies))
        .route("/greek-pantheon", get(greek_pantheon))
        .route("/greek-pantheon/:slug", get(greek_deity))
}

async fn hub() -> impl IntoResponse {
    HtmlTemplate(EsotericMythologiesCosmologiesTemplate)
}

async fn gnostic_aeons() -> impl IntoResponse {
    HtmlTemplate(GnosticAeonsTemplate)
}

async fn demiurge_myth() -> impl IntoResponse {
    HtmlTemplate(DemiurgeMythTemplate)
}

async fn sophia_traditions() -> impl IntoResponse {
    HtmlTemplate(SophiaTraditionsTemplate)
}

async fn tree_of_life_cosmology() -> impl IntoResponse {
    HtmlTemplate(TreeOfLifeCosmologyTemplate)
}

async fn emanation_theories() -> impl IntoResponse {
    HtmlTemplate(EmanationTheoriesTemplate)
}

async fn platonic_world_soul() -> impl IntoResponse {
    HtmlTemplate(PlatonicWorldSoulTemplate)
}

async fn astral_planes() -> impl IntoResponse {
    HtmlTemplate(AstralPlanesTemplate)
}

async fn chakric_systems() -> impl IntoResponse {
    HtmlTemplate(ChakricSystemsTemplate)
}

async fn sephirothic_hierarchies() -> impl IntoResponse {
    HtmlTemplate(SephirothicHierarchiesTemplate)
}

async fn greek_pantheon() -> impl IntoResponse {
    HtmlTemplate(GreekPantheonTemplate {
        deities: GREEK_DEITIES,
    })
}

async fn greek_deity(Path(slug): Path<String>) -> impl IntoResponse {
    match GREEK_DEITIES.iter().find(|deity| deity.slug == slug) {
        Some(deity) => (StatusCode::OK, HtmlTemplate(GreekDeityTemplate { deity })).into_response(),
        None => (StatusCode::NOT_FOUND, "Greek deity page not found").into_response(),
    }
}
